CREATE USER IF NOT EXISTS 'alpha'@'%' IDENTIFIED BY 'alphapassword';
GRANT ALL PRIVILEGES ON *.* TO 'alpha'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS volunteer;

SHOW DATABASES;
