name: Build, Test, and Publish Release

env:
  TZ: 'America/New_York'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

on:
  push:
   branches:
      - 'main'
      - 'release*'
      - '*'

  pull_request:
    branches:
      - 'main'
      - 'release*'
      - '*'
  release:
    types: [ published ]
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9",  "3.10" ]
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Compose services
        env:
          POSTGRES_DB: demo_db
          POSTGRES_USER: alpha
          POSTGRES_PASSWORD: developer
          POSTGRES_VERSION: 13
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          MYSQL_DATABASE: demo_db
          MYSQL_USER: alpha
          MYSQL_PASSWORD: developer
          MYSQL_ROOT_PASSWORD: developer
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MARIADB_DATABASE: demo_db
          MARIADB_USER: alpha
          MARIADB_PASSWORD: developer
          MARIADB_ROOT_PASSWORD: developer
          MARIADB_HOST: localhost
          MARIADB_PORT: 3307
        run: |          
          printf """
          # ##########################################################
          LOG_LEVEL="DEBUG"
          # ##########################################################
          MARIADB_DATABASE=$MARIADB_DATABASE
          MARIADB_USER=$MARIADB_USER
          MARIADB_PASSWORD=$MARIADB_PASSWORD
          MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
          MARIADB_ROOT_PASSWORD_HASH=""
          MARIADB_HOST=$MARIADB_HOST
          MARIADB_PORT=$MARIADB_PORT
          # ##########################################################
          MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE=$MYSQL_DATABASE
          MYSQL_USER=$MYSQL_USER
          MYSQL_PASSWORD=$MYSQL_PASSWORD
          MYSQL_ALLOW_EMPTY_PASSWORD=no
          MYSQL_RANDOM_ROOT_PASSWORD=no
          MYSQL_ONETIME_PASSWORD=no
          MYSQL_INITDB_SKIP_TZINFO=no
          MYSQL_HOST=$MYSQL_HOST
          MYSQL_PORT=$MYSQL_PORT
          # ##########################################################
          POSTGRES_DB=$POSTGRES_DB
          POSTGRES_USER=$POSTGRES_USER
          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          POSTGRES_INITDB_ARGS=""
          POSTGRES_INITDB_WALDIR=""
          POSTGRES_HOST_AUTH_METHOD=scram-sha-256
          PGDATA=/var/lib/postgresql/data
          POSTGRES_PORT=$POSTGRES_PORT
          POSTGRES_VERSION=$POSTGRES_VERSION
          POSTGRES_HOST=$POSTGRES_HOST
          """ > .env
        
          # Start the services
          docker compose -p crudrepository up \
          --always-recreate-deps \
          --renew-anon-volumes \
          --remove-orphans \
          --force-recreate \
          -d --build && wait $!
          
          # List the services
          docker ps -a

      # Task for linting with black
      - name: Lint with black
        run: |
          /bin/bash deploy.sh -uv --install-dev && wait $!
          # Code formatting with black, check every python file in the crud_repository directory 
          black crud_repository
          black --check crud_repository

      # Task for running tests
      - name: Testing with pytest
        run: |
          # List the services
          docker ps -a && wait $!
          # Inspect the services
          docker inspect crudrepository-mysql-1 && wait $!
          docker inspect crudrepository-postgres-1 && wait $!
          docker inspect crudrepository-maria-1 && wait $!
          
          # curl each service to ensure they are running
          curl -s -o /dev/null http://localhost:3306
          curl -s -o /dev/null http://localhost:3307
          curl -s -o /dev/null http://localhost:5432
          
          if python3 -m pytest tests/ 2>&1 ; then
              echo "Tests completed Successfully."
          else
              echo "Tests failed to complete successfully."
              exit 1
          fi

  build-and-publish:
    needs: setup-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9",  "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build package artifact
        run: |
          /bin/bash deploy.sh --install-dev --build && wait $!
          echo "Build completed Successfully."

      - name: Upload build artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v2
        with:
          name: Build-Results
          path: |
            dist
            crud_repository.egg-info
            README.md
            LICENSE

      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
            printf """\n
            [pypi]
            repository: https://upload.pypi.org/legacy/
            username = $TWINE_USERNAME
            password = $TWINE_PASSWORD
              """ > ~/.pypirc
              python3 -m twine upload \
              --verbose --skip-existing --non-interactive \
              --config-file ~/.pypirc \
              dist/* &> /dev/null
              echo "Published to PyPI Successfully."
