name: Build test and deploy to package repository
env:
  TZ: 'America/New_York'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9",  "3.10" ]
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          poetry install

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9",  "3.10" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Compose services
        run: |
          printf """
          LOG_LEVEL="DEBUG"
          MARIADB_DATABASE=testdb
          MARIADB_USER=alpha
          MARIADB_PASSWORD=alphapassword
          MARIADB_ROOT_PASSWORD=alphapassword
          MARIADB_ROOT_PASSWORD_HASH=""
          MARIADB_HOST="127.0.0.1"
          MARIADB_PORT=3307
          # ##########################################################
          MYSQL_ROOT_PASSWORD=alphapassword
          MYSQL_DATABASE=testdb
          MYSQL_USER=alpha
          MYSQL_PASSWORD=alphapassword
          MYSQL_ALLOW_EMPTY_PASSWORD=no
          MYSQL_RANDOM_ROOT_PASSWORD=no
          MYSQL_ONETIME_PASSWORD=no
          MYSQL_INITDB_SKIP_TZINFO=no
          MYSQL_HOST="127.0.0.1"
          MYSQL_PORT=3306
          # ##########################################################
          POSTGRES_DB=testdb
          POSTGRES_USER=alpha
          POSTGRES_PASSWORD=alphapassword
          POSTGRES_INITDB_ARGS=
          POSTGRES_INITDB_WALDIR=
          POSTGRES_HOST_AUTH_METHOD=scram-sha-256
          PGDATA=/var/lib/postgresql/data
          POSTGRES_PORT=5432
          POSTGRES_VERSION=13
          POSTGRES_HOST="127.0.0.1"
          # ##########################################################
          """ > .env
          cat .env
          docker-compose up -d
          sleep 60
      # Task for installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest wheel setuptools build twine poetry

          if [ -f requirements.txt ]; then pip install  -r requirements.txt ; fi 

      # Task for linting with black
      - name: Lint with black
        run: |
          # Code formatting with black, check every python file in the src directory 
          black src
          black --check src

      - name: Build and test
        run: |
          poetry build
          poetry run pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9",  "3.10" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload build artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v2
        with:
          name: Build-Results
          path: |
            dist
            crud_repository.egg-info
            README.md
            LICENSE

#      - name: Publish to PyPI
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
#        run: |
#          poetry publish --build -u $TWINE_USERNAME -p $TWINE_PASSWORD &>/dev/null
